# Generated by Django 2.0.6 on 2018-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('semester', 'course_id')},
        ),
    ]
