# Generated by Django 2.0.6 on 2018-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=10)),
                ('ge_type', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('outline_link', models.CharField(max_length=128)),
                ('credit', models.IntegerField()),
                ('required_subject', models.BooleanField()),
                ('lecturer', models.CharField(max_length=50)),
                ('classroom', models.CharField(max_length=50)),
                ('periods', models.CharField(max_length=1024)),
                ('note', models.TextField()),
            ],
        ),
    ]
